version: '2.1'
services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch-master
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

  elasticsearch-slave-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    depends_on:
      - elasticsearch-master
    container_name: elasticsearch-slave-1
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch-master
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - node.master=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.1.2
    depends_on:
      - elasticsearch-master
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-master:9200
      - xpack.security.enabled=false
    networks:
      - esnet

  logstash:
    image: 8x8cloud/logstash-in-a-box:5.x
    depends_on:
      - elasticsearch-master
    volumes:
      - "${LOG_DIR:-./data}:/input:ro"
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge
